# Generated by Django 5.0.3 on 2024-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_category_en',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_of_news_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_of_news_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
